version: '3.5'

services:
  databasemysql:
    container_name: db12
    image: mysql:5.7
    ports:
      - 1234:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: always
    networks: 
      - microservices
  productservice:
    container_name: productService
    build:
      context: ./
      dockerfile: ./Dockerfile-product-service
    ports:
      - 3303:3303
    networks: 
      - microservices
    depends_on:
      - databasemysql
  customerservice:
    container_name: customerService
    build:
       context: ./
       dockerfile: ./Dockerfile-customer-service
    ports:
      - 3302:3302
    networks: 
      - microservices
    depends_on:
      - databasemysql
  creditservice:
    container_name: creditService
    build:
      context: ./
      dockerfile: ./Dockerfile-credit-service
    ports:
     - 3301:3301
    networks: 
     - microservices
    depends_on:
     - databasemysql

networks: 
  microservices:
    driver: bridge